Repository TBD54566975/web5-js, pull requests merged in 2023-12, with the labels that each got.

#339 Add JWT and DID `dereference()`
  .web5-spec/credentials.ts
  package-lock.json
  packages/credentials/package.json
  packages/credentials/src/index.ts
  packages/credentials/src/jwt.ts
  packages/credentials/src/presentation-exchange.ts
  packages/credentials/src/utils.ts
  packages/credentials/src/validators.ts
  packages/credentials/src/verifiable-credential.ts
  packages/credentials/tests/jwt.spec.ts
  packages/credentials/tests/presentation-exchange.spec.ts
  packages/credentials/tests/ssi-validator.spec.ts
  packages/credentials/tests/verifiable-credential.spec.ts
  packages/crypto/package.json
  packages/crypto/src/jose.ts
  packages/crypto/src/utils.ts
  packages/crypto/tests/utils.spec.ts
  packages/dids/src/did-resolver.ts
  packages/dids/src/types.ts
  packages/dids/src/utils.ts
  packages/dids/tests/did-resolver.spec.ts
Labels: enhancement, dependencies, credentials

#325 speed up ci
  .github/workflows/alpha-npm.yml
  .github/workflows/docs-ci.yml
  .github/workflows/docs-publish.yml
  .github/workflows/release-npm.yml
  .github/workflows/scorecard.yml
  .github/workflows/security.yml
  .github/workflows/tests-ci.yml
  package-lock.json
  package.json
  packages/agent/web-test-runner.config.cjs
Labels: cicd

#345 Fix record author bug
  packages/agent/src/dwn-manager.ts
  packages/api/src/dwn-api.ts
  packages/api/src/record.ts
  packages/api/tests/record.spec.ts
Labels: bug

#349 Update `@web5/credentials` README
  packages/credentials/README.md
  packages/credentials/src/presentation-exchange.ts
  packages/credentials/src/verifiable-credential.ts
  packages/credentials/tests/presentation-exchange.spec.ts
Labels: documentation

#353 Bump `@web5/dids` version and improve DID spec compliance
  package-lock.json
  packages/agent/package.json
  packages/api/package.json
  packages/credentials/package.json
  packages/credentials/tests/verifiable-credential.spec.ts
  packages/dids/package.json
  packages/dids/src/did-dht.ts
  packages/dids/src/did-ion.ts
  packages/dids/src/did-key.ts
  packages/dids/src/did-resolver.ts
  packages/dids/src/types.ts
  packages/dids/tests/did-dht.spec.ts
  packages/dids/tests/did-resolver.spec.ts
  packages/identity-agent/package.json
  packages/proxy-agent/package.json
  packages/user-agent/package.json
Labels: documentation, dependencies
