Repository TBD54566975/web5-js, pull requests merged in 2023-11, with the labels that each got.

#257 Remove usage of named exports until React Native supports
  packages/agent/src/app-data-store.ts
  packages/agent/src/dwn-manager.ts
  packages/agent/src/kms-local.ts
  packages/agent/src/rpc-client.ts
  packages/agent/src/store-managed-key.ts
  packages/api/src/tech-preview.ts
  packages/api/tests/record.spec.ts
  packages/api/tests/utils/test-data-generator.ts
  packages/dids/src/did-key.ts
Labels: enhancement

#262 Add PBKDF2 to `@web5/crypto`
  packages/agent/src/app-data-store.ts
  packages/agent/src/types/managed-key.ts
  packages/crypto/src/algorithms-api/crypto-key.ts
  packages/crypto/src/algorithms-api/index.ts
  packages/crypto/src/algorithms-api/pbkdf/index.ts
  packages/crypto/src/algorithms-api/pbkdf/pbkdf2.ts
  packages/crypto/src/crypto-algorithms/index.ts
  packages/crypto/src/crypto-algorithms/pbkdf2.ts
  packages/crypto/src/crypto-primitives/index.ts
  packages/crypto/src/crypto-primitives/pbkdf2.ts
  packages/crypto/src/jose.ts
  packages/crypto/src/types/web5-crypto.ts
  packages/crypto/src/utils.ts
  packages/crypto/tests/algorithms-api.spec.ts
  packages/crypto/tests/crypto-algorithms.spec.ts
  packages/crypto/tests/crypto-primitives.spec.ts
  packages/crypto/tests/utils.spec.ts
Labels: enhancement

#267 Re-introduce `resolve` Method in `DidApi` for DID Resolution
  README.md
  package-lock.json
  packages/agent/package.json
  packages/agent/src/did-manager.ts
  packages/agent/src/dwn-manager.ts
  packages/agent/src/rpc-client.ts
  packages/agent/src/types/agent.ts
  packages/agent/tests/utils/test-agent.ts
  packages/api/README.md
  packages/api/package.json
  packages/api/src/did-api.ts
  packages/api/tests/did-api.spec.ts
  packages/api/tests/utils/test-user-agent.ts
  packages/credentials/package.json
  packages/crypto/package.json
  packages/dids/build/cjs-bundle.js
  packages/dids/package.json
  packages/identity-agent/src/identity-agent.ts
  packages/proxy-agent/package.json
  packages/proxy-agent/src/proxy-agent.ts
  packages/user-agent/package.json
  packages/user-agent/src/user-agent.ts
Labels: enhancement

#290 Bump dwn-sdk-js version to 0.2.6 and fix bugs
  package-lock.json
  packages/agent/.vscode/launch.json
  packages/agent/package.json
  packages/agent/src/dwn-manager.ts
  packages/agent/src/types/agent.ts
  packages/agent/tests/test-config.ts
  packages/api/package.json
  packages/api/src/dwn-api.ts
  packages/api/src/record.ts
  packages/api/tests/dwn-api.spec.ts
  packages/api/tests/record.spec.ts
  packages/api/tests/test-config.ts
  packages/crypto/src/jose.ts
  packages/dev-env/docker-compose.yaml
  packages/identity-agent/package.json
  packages/identity-agent/src/identity-agent.ts
  packages/proxy-agent/package.json
  packages/proxy-agent/src/proxy-agent.ts
  packages/user-agent/package.json
Labels: bug, documentation, dependencies

#297 Incorrect MessageOptions for `RecordsRead` requests in sync manager.
  packages/agent/src/dwn-manager.ts
  packages/agent/src/rpc-client.ts
  packages/agent/src/sync-manager.ts
  packages/agent/tests/sync-manager.spec.ts
Labels: bug

#298 Fix bug with `record.data.*` after record queries
  packages/agent/tests/dwn-manager.spec.ts
  packages/api/src/dwn-api.ts
  packages/api/src/record.ts
  packages/api/tests/dwn-api.spec.ts
  packages/api/tests/record.spec.ts
Labels: bug

#299 Bump readable-stream types dependency
  package-lock.json
  packages/agent/package.json
  packages/api/package.json
Labels: dependencies

#300 Fix bug that was causing record.send() and record.update() issues
  packages/api/src/record.ts
  packages/api/tests/record.spec.ts
Labels: bug

#304 fix Single-quoted string interpolation in src/web5.ts
  packages/api/src/web5.ts
Labels: bug

#322 Test for did:dht signed VCs + release
  package-lock.json
  packages/api/package.json
  packages/credentials/package.json
  packages/credentials/tests/verifiable-credential.spec.ts
  packages/identity-agent/package.json
Labels: testing

#268 Support RecordsQuery pagination in Web5
  README.md
  packages/agent/src/sync-manager.ts
  packages/api/README.md
  packages/api/src/dwn-api.ts
  packages/api/tests/dwn-api.spec.ts
Labels: enhancement
