Repository TBD54566975/web5-js, pull requests merged in 2024-03, with the labels that each got.

#441 Fix path Esbuild config to run all browser tests
  packages/agent/build/esbuild-tests.cjs
  packages/api/build/esbuild-tests.cjs
  packages/common/build/esbuild-tests.cjs
  packages/credentials/build/esbuild-tests.cjs
  packages/crypto/build/esbuild-tests.cjs
  packages/crypto/src/primitives/aes-gcm.ts
  packages/crypto/tests/algorithms/aes-ctr.spec.ts
  packages/crypto/tests/algorithms/aes-gcm.spec.ts
  packages/crypto/tests/primitives/aes-ctr.spec.ts
  packages/crypto/tests/primitives/aes-gcm.spec.ts
  packages/crypto/tests/utils/runtimes.ts
  packages/dids/build/esbuild-tests.cjs
  packages/dids/package.json
  packages/dids/tests/methods/did-key.spec.ts
  packages/dids/tests/resolver/resolver-cache-level.spec.ts
  packages/identity-agent/build/esbuild-tests.cjs
  packages/proxy-agent/build/esbuild-tests.cjs
  packages/user-agent/build/esbuild-tests.cjs
  pnpm-lock.yaml
Labels: testing

#446 Fix VSCode workspace paths after switch to pnpm
  packages/agent/.vscode/launch.json
  packages/api/.vscode/launch.json
  packages/common/.vscode/launch.json
  packages/credentials/.vscode/launch.json
  packages/crypto-aws-kms/.vscode/launch.json
  packages/crypto/.vscode/launch.json
  packages/dids/.vscode/launch.json
  packages/identity-agent/.vscode/launch.json
  packages/proxy-agent/.vscode/launch.json
  packages/user-agent/.vscode/launch.json
Labels: testing

#442 Move SDK reporting to separate workflow job
  .github/workflows/reports.yml
  .github/workflows/tests-ci.yml
Labels: testing, cicd

#451 Update `dids` package CJS bundling
  packages/dids/build/cjs-bundle.js
Labels: package: dids

#454 Add DID resolution types and rename UniversalResolver
  packages/dids/src/index.ts
  packages/dids/src/methods/did-dht.ts
  packages/dids/src/methods/did-ion.ts
  packages/dids/src/methods/did-jwk.ts
  packages/dids/src/methods/did-key.ts
  packages/dids/src/methods/did-web.ts
  packages/dids/src/resolver/resolver-cache-level.ts
  packages/dids/src/resolver/resolver-cache-noop.ts
  packages/dids/src/resolver/universal-resolver.ts
  packages/dids/src/types/did-resolution.ts
  packages/dids/tests/resolver/resolver-cache-level.spec.ts
  packages/dids/tests/resolver/universal-resolver.spec.ts
Labels: package: dids

#471 Fix for CVE-2024-29041
  package.json
  pnpm-lock.yaml
Labels: security
